# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.1.2
group=com.cursee.danger_close
java_version=21

# Common
minecraft_version=1.21.1
parchment_version=2024.11.17
mod_name=Danger Close
mod_author=Lupin, Jason13
mod_id=danger_close
license=Unlicense
credits=Thanks to Jared(MultiLoader-Template), Darkhax(Bookshelf), Serilum(Collective) and PacifistMC(Forgix).
description=You're standing a little close to that torch!
minecraft_version_range=[1.21.1, 1.22)


# Fabric
fabric_version=0.114.0+1.21.1
fabric_loader_version=0.16.10

# Forge
forge_version=52.0.40
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.107
neoforge_loader_version_range=[4,)

# Compatibility
soul_fire_d_version=5.1.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
